config/routes.rb
Bannermaker::Application.routes.draw do
  resources :campaigns

  root 'landing#index'

  namespace :landing do
    get 'advertiser'
    get 'publisher'
    get 'about_us'
    get 'contacts'
  end

  resource :users, only: [] do
    get 'sign_up'
    get 'sign_in'
    delete 'sign_out'
    post 'create'
    post 'login'
  end

  namespace :publisher do
    root 'sites#index'

    resources :sites
    resources :zones do
      member do
        get 'get_code'
      end
    end

  end

  namespace :advertiser do
    root 'main#index'

    resource :payments, only: [] do
      get 'some_action'
    end
  end

  get 'othersite', to: 'other_site#index'
  get  'test',    to: 'other_site#test_get'
  post 'test',    to: 'other_site#test_post'
  put  'test',    to: 'other_site#test_put'
  delete 'test',  to: 'other_site#test_delete'

end

app/views/shared/_affilate.html.erb
<!-- Affilate -->
<div id="affilate-tab-content" class="box tab-content-js">
  no info
</div>
<!-- /Affilate -->

app/views/shared/_sign_in_form.html.erb
<!-- login / login modal -->
  <div class="hd5">Login</div>
  <%= image_tag 'pp_logo.png', class: 'pp_logo' %>

<% remote = (defined? remote_sign_in) && remote_sign_in  %>

<form action="<%= login_users_path(format: remote ? :json : nil) %>" method="post" id="sign_in" class="sign_form" <%= remote ? 'data-remote="true"' : '' %> data-validate="true" data-action="users_login">
<fieldset>
  <div class="form_in">
    <label>Login:</label>
    <input type="text" class="input" name="user[username]" autocomplete="off"  value="<%= user.username %>">

    <label>Password:</label>
    <input type="password" class="input" name="user[password]" autocomplete="off"  value="<%= user.password %>">


    <label>Your Role:</label>
    <select type="text" class="input" autocomplete="off" name="user[role]" value="<%= user.role %>">
      <option value=""></option>
      <option <%= "#{'selected' if user.role_advertiser?}"%> value="ADVERTISER">ADVERTISER</option>
      <option <%= "#{'selected' if user.role_publisher?}"%> value="PUBLISHER">PUBLISHER</option>
    </select>
    <!--<label>Confirm password:</label>-->
    <!--<input type="password" class="input">-->

    <div class="checks2">
      <label class="label_check" for="rem"><input name="remember" id="rem" value="1" type="checkbox" checked=""><span>Remember?</span></label>
      <a id="forgot_password" href="#" title="">Forgot password</a>
    </div>
  </div>
</fieldset>
<div class="but5">
  <input type="submit" value="Login" class="button b9">
</div>
</form>
<!-- /login modal -->

app/views/shared/_sign_up_form.html.erb
<!-- sign up / sign up modal -->
<div class="hd5">Sign Up</div>
<%= image_tag 'pp_logo.png', class: 'pp_logo' %>

<% remote = (defined? remote_sign_up) && remote_sign_up %>

<form action="<%= users_path(format: remote ? :json : nil) %>" method="post" id="sign_up" class="sign_form " data-validate="true" <%= remote ? 'data-remote="true"' : '' %> data-action="users_create">
  <fieldset>
    <div class="form_in">

      <label>Login:*</label>
      <input type="text" class="input" autocomplete="off" name="user[username]" value="<%= user.username %>">

      <label>Email:*</label>
      <input type="text" class="input" autocomplete="off" name="user[email]" value="<%= user.email %>">

      <label>Password:*</label>
      <input type="password" class="input" autocomplete="off"  name="user[password]" value="<%= user.password %>">

      <label>Confirm password:*</label>
      <input type="password" class="input" autocomplete="off" name="user[password_confirmation]" >

      <label>Choose your role:*</label>
      <select type="text" class="input" autocomplete="off" name="user[role]" value="<%= user.role %>">
        <option value="ADVERTISER">ADVERTISER</option>
        <option value="PUBLISHER">PUBLISHER</option>
      </select>

      <label>Phone:*</label>
      <input type="text" placeholder="+22(345)7891012" class="input" autocomplete="off" name="user[phone]" value="<%= user.phone %>">

      <label>First Name:*</label>
      <input type="text" class="input" autocomplete="off" name="user[firstName]" value="<%= user.firstName %>">

      <label>Last Name:*</label>
      <input type="text" class="input" autocomplete="off" name="user[lastName]" value="<%= user.lastName %>">

      <label>Website Url:*</label>
      <input type="text" class="input" autocomplete="off" name="user[websiteUrl]" placeholder="http://google.com" value="<%= user.websiteUrl %>">


      <!--<label>Company name:</label>-->
      <!--<input type="text" class="input" name="company">-->

      <!--<label>Country:</label>-->
      <!--<input type="text" class="input" name="country">-->

      <!--<label>State:</label>-->
      <!--<input type="text" class="input" name="state">-->

      <div class="checks">
        <input type="checkbox" id="note"  name="user[notify]"><label for="note">System notification</label>
        <input type="checkbox" id="newsletter" name="user[newsletter]"><label for="newsletter">Free newsletter</label>
      </div>
    </div>

    <p>Start the Traffic Exchange experience today!</p>
  </fieldset>
  <div class="but5">
    <input type="submit" value="Sign Up" class="button b9">
  </div>
</form>