config/routes.rb
Bannermaker::Application.routes.draw do
  resources :campaigns

  root 'landing#index'

  namespace :landing do
    get 'advertiser'
    get 'publisher'
    get 'about_us'
    get 'contacts'
  end

  resource :users, only: [] do
    get 'sign_up'
    get 'sign_in'
    delete 'sign_out'
    post 'create'
    post 'login'
  end

  namespace :publisher do
    root 'sites#index'

    resources :sites
    resources :zones do
      member do
        get 'get_code'
      end
    end

  end

  namespace :advertiser do
    root 'main#index'

    resource :payments, only: [] do
      get 'some_action'
    end
  end

  get 'othersite', to: 'other_site#index'
  get  'test',    to: 'other_site#test_get'
  post 'test',    to: 'other_site#test_post'
  put  'test',    to: 'other_site#test_put'
  delete 'test',  to: 'other_site#test_delete'

end

app/models/zone.rb
class Zone < ActiveRecord::Base

  validates :name, presence: true


end

app/controllers/publisher/main_controller.rb
class Publisher::MainController < ApplicationController

  before_action :check_access
  before_action :check_custom_flash, only: :index

  include PublisherSitesApi

  layout 'application'

  def index
  end

  private

  def check_access
    redirect_to sign_in_users_path, flash: { error: t(:unauthenticated, scope: [:devise, :failure]) } if (!current_user || !current_user.role_publisher?)
  end
end

app/controllers/publisher/sites_controller.rb
class Publisher::SitesController < Publisher::MainController

  before_action :set_obj_name, only: [:index, :edit, :destroy]

  def index
    @form_data_action = "#{@obj_name_plur}_create"
    @form_id = "#{@form_data_action}_form"
    @form_method = 'post'

    # для создания нового объекта в модальном окне
    instance_variable_set("@#{@obj_name}", @obj_name.camelize.constantize.new)

    # Категории для сайта
    get_categories

    # GET SITES for PUBLISHER
    @response = get_sites(current_user.username, current_user.hashed_password)
    response_handler

    if @api_success
      @sites = @response
      @sites = @sites.uniq
      set_sites_hash_by_id(@sites)
    else
      errors_resolver(nil, {redirect_to: public_send("root_path")})
    end

    return if performed?
  end

  def new
  end

  def create
    create_or_update('create')
  end

  def update
    create_or_update('update')
  end

  def create_or_update(action_str)
    # binding.pry
    @site = Site.new(send("#{action_str}_params"))

    @site = set_new_site_defaults @site

    # validation
    if @site.valid?
      api_params = @site.attributes
      api_params.delete('revenueShare') if Site::CPM_ONLY


      @response = create_or_update_site(api_params, action_str)
      response_handler
    else
      @validate_errors = true
    end

    if @api_success
      api_success_handler({redirect_to: publisher_sites_path}, t("site_#{action_str}_success"))
    else

      if action_str == 'create'
        errors_resolver(@site, {render: :new})
      else
        # так как на списке у нас в формах объект для создания: @zone - по имени модели
        # а для редатирования: @edit_obj
        @edit_obj = @site
        errors_resolver(@edit_obj, {render: :edit})
      end

    end

    return if performed?
  end

  def edit
    @form_data_action = "#{@obj_name_plur}_update"
    @form_id = "#{@form_data_action}_form"
    @form_method = 'put'

    @edit_obj = @obj_name.camelize.constantize.new(edit_params)

    # Категории для сайта
    get_categories

    render layout: false
  end

  def destroy
    @response = delete_site(params[:id])
    response_handler

    if @api_success
      api_success_handler({redirect_to: publisher_sites_path}, t("delete_#{@obj_name}_success"))
    else
      errors_resolver(nil, {redirect_to: publisher_sites_path})
    end

    return if performed?
  end

  private

  def create_params
    ActionController::Parameters.new(params).require(:site).permit(
        :id,
        :name,
        :url,
        :description,
        :email,
        :allowPlacementBannersLinkingChange,
        :revenueShare,
        :impressionsByMonth,
        :visitorsByMonth,
        :createDefaultZone,
        :categoryId => []
    )
  end

  def update_params
    create_params
  end

  def edit_params
    ActionController::Parameters.new(params).require(:edit_obj).permit(
        :id,
        :name,
        :url,
        :description,
        :email,
        :impressionsByMonth,
        :visitorsByMonth,
        :categoryId => []
    )
  end


  def set_new_site_defaults obj
    # не разрешаем паблишеру самостоятельно крепить к себе баннеры
    obj[:allowPlacementBannersLinkingChange] = false

    obj
  end

  def set_sites_hash_by_id sites
    obj = {}
    sites.each do |site|
      obj[site['id']] = site
    end

    gon.push({publisher: {sites: obj} })
  end

  def get_categories
    # Категории для сайта
    @response = get_publishing_categories
    response_handler
    @pub_categories = @response
  end
end

app/controllers/publisher/zones_controller.rb
class Publisher::ZonesController < Publisher::MainController

  include PublisherZonesApi
  include PublisherPlacementsApi

  before_action :set_obj_name, only: [:index, :edit, :destroy]

  def index
    # такое же название формируется при обработке ошибок и передается в js
    @form_data_action = "#{@obj_name_plur}_create"
    @form_id = "#{@form_data_action}_form"
    @form_method = 'post'

    # ADD ZONE | для создания нового объекта в модальном окне
    instance_variable_set("@#{@obj_name}", @obj_name.camelize.constantize.new) # @zone = Zone.new

    # GET ZONES for Site
    @siteId = params['siteId']

    # Placement obj
    @placement = Placement.new

    @response = get_zones(current_user.username, current_user.hashed_password, @siteId)
    response_handler

    if @api_success
      @zones = @response.uniq
      current_site_zones_hash(@zones)
    else
      errors_resolver(nil, {redirect_to: publisher_sites_path})
    end

    return if performed?
  end

  def new
  end

  def create
    create_or_update('create')
  end

  def update
    create_or_update('update')
  end

  def create_or_update(action_str)
    @zone = Zone.new(send("#{action_str}_params"))

    # validation
    if @zone.valid?
      api_params = @zone.attributes

      @response = create_or_update_zone(api_params, action_str)
      response_handler

      #  далее нужно будет объединить данные от зоны и от плэйсмента
      @zone_response = @response
    else
      @validate_errors = true
    end


    if @api_success

      # работаем с плэйсментом уже без обработки ошибок так как там все обязательные парметры стоят по дефолту
      @placement = Placement.new(send("placement_#{action_str}_params"))
      api_params = @placement.attributes
      api_params['zoneId'] = @zone_response['id']

      @response = create_or_update_placement(api_params, action_str)
      response_handler

      if @api_success
        # от апи получили только id placement
        placement_id = @response['id']

        # берем ответ зоны там ее id и добавляем placement_id
        @response = @zone_response
        # убрано так как плэйсмент id при редактировании все равно обычно дергаем по апи
        # @response['placement_id'] = placement_id

        api_success_handler({redirect_to: publisher_zones_path( siteId: params.require(:zone)[:siteId] )}, t("zone_#{action_str}_success"))
      else
        if action_str == 'create'
          errors_resolver(@zone, {render: :new})
        else
          @edit_obj = @zone
          @edit_placement = @placement
          errors_resolver(@edit_obj, {render: :edit})
        end
      end

    else

      if action_str == 'create'
        errors_resolver(@zone, {render: :new})
      else
        # так как на списке у нас в формах объект для создания: @zone - по имени модели
        # а для редатирования: @edit_obj
        @edit_obj = @zone
        errors_resolver(@edit_obj, {render: :edit})
      end

    end

    return if performed?
  end

  def edit
    @form_data_action = "#{@obj_name_plur}_update"
    @form_id = "#{@form_data_action}_form"
    @form_method = 'put'

    @siteId = params['siteId']

    @edit_obj = @obj_name.camelize.constantize.new(edit_params)
    @edit_placement = Placement.new(placement_edit_params)

    # Для получения id плэйсмента для редактирования
    @response = get_zone_placements(@edit_obj.id)
    response_handler

    if @api_success && ((@response.is_a? Array) && (@response.length == 0))
      @api_success = false
      @custom_msg = t :zone_not_found
    end

    if  @api_success
      # мы соединили 1 плэйсмент для 1-й зоны поэтому берем первый id из массива
      @edit_placement['id'] = @response[0]['id']

      render layout: false
    else
      #  так как запрос на модалку не .json то ответ ошибки не пройдет по format.json - мы насильно говорим что ответ дать в форме json
      @force_json_response = true
      errors_resolver(@zone, {redirect_to: publisher_zones_path})
    end
  end

  def destroy
    @response = delete_zone(params[:id])
    response_handler

    if @api_success
      api_success_handler({redirect_to: publisher_zones_path( siteId: params[:siteId] )}, t("delete_#{@obj_name}_success"))
    else
      errors_resolver(nil, {redirect_to: publisher_zones_path( siteId: params[:siteId] )})
    end

    return if performed?
  end

  # INVOCATION CODE
  def get_code
    # Для получения id плэйсмента
    @response = get_zone_placements(params['id'])
    response_handler

    if @api_success
      placement_id = @response[0]['id']
      @epom_key = build_epom_key(params['siteId'], params['id'], placement_id)
      render layout: false
    else
      @force_json_response = true
      errors_resolver(nil, {redirect_to: publisher_zones_path})
    end

    return if performed?
  end

  private


  # ZONE PARAMS--------------------------------------
  def create_params
    params.require(:zone).permit(
        :id,
        :name,
        :description,
        :siteId
    )
  end

  def update_params
    create_params
  end

  def edit_params
    params.require(:edit_obj).permit(
        :id,
        :name,
        :description,
        :siteId
    )
  end



  # PLACEMENT PARAMS----------------------------------
  def placement_create_params
    params.require(:zone).permit(
        :placement_id,
        :name,          # это будет имя и описание зоны но это нормально пусть совпадают - юзер видит только имя зоны
        :description,   #
        :zoneId,
        :size_adUnit,
        :defaultCode,
        :size_height,
        :size_width
    )
  end

  def placement_update_params
    p = placement_create_params

    # эта часть параметров - относится к плэйсмент но так как мы берем парамсы из create -  - это id зоны - заменяем на placement_id
    p['id'] = params.require(:zone)['placement_id']
    p.delete 'placement_id'

    p
  end

  def placement_edit_params
    # ! edit_obj
    params.require(:edit_obj).permit(
        :id,
        :name,
        :description,
        :zoneId,
        :size_adUnit,
        :defaultCode,
        :size_height,
        :size_width

    )
  end


  def current_site_zones_hash zones
    obj = {}
    zones.each do |zone|
      obj[zone['id']] = zones
    end

    gon.push({publisher: {current_site: {zones: obj} }})
  end

  def build_epom_key(site_id, zone_id, placement_id)
    str = "#{site_id}|#{zone_id}|#{placement_id}"
    md5_hash(str)
  end

  def build_inv_code
  end
end

app/views/publisher/zones/_add_zone_modal.html.erb
<div id='<%= "add#{@obj_name.camelize}Modal" %>' class="reveal-modal">

    <span class="close-reveal-modal close2"></span>
    <h2>New <%= @obj_name %></h2>
    <div class="spr2"></div>

  <%= render "publisher/#{@obj_name_plur}/form", obj: obj, placement: placement, remote: true  %>

</div>

app/views/publisher/zones/_edit_zone_modal.html.erb
<!-- Предполагается что для любого объекта и даже действия СВОЕ модальное окно - мы не делаем запрос данных если в него они однажды были загружены-->
<div id='<%="edit#{obj_name.camelize}Modal" %>' class="reveal-modal" data-loaded="">

    <span class="close-reveal-modal close2"></span>
    <h2>Edit <%= "#{obj_name}"%></h2>
    <div class="spr2"></div>

    <div class="modal_content">

    </div>
</div>

app/views/publisher/zones/_form.html.erb
<!--FOR CREATE(new form) AND UPDATE(edit form)-->

<% in_modal = (defined? remote) && remote  %>

<% if @form_method == 'post' %>
    <% standard_action = 'create' %>
    <% action = public_send("publisher_#{@obj_name.pluralize}_path", {format: in_modal ? :json : nil})  %>
<% end %>

<% if @form_method == 'put' %>
    <% standard_action = 'update' %>
    <% action = public_send("publisher_#{@obj_name}_path", {id: obj.id, format: in_modal ? :json : nil})  %>
<% end %>


<form id="<%= @form_id %>" action="<%= action %>" method="<%= @form_method %>" <%= in_modal ? 'data-remote=true' : '' %> class="form pp_form" data-validate="true" data-action="<%= @form_data_action %>" data-standard-action="<%= standard_action %>" data-model-name="<%= @obj_name %>" data-model-name="<%= @obj_name %>" data-model-plur-name="<%= @obj_name_plur %>" >
  <fieldset>
    <% if obj.id %>
        <input type="text" class="none" name=<%= "#{@obj_name}[id]" %> value="<%= obj.id %>">
    <% end %>

    <label>Name*</label>
    <input type="text" class="input" name=<%= "#{@obj_name}[name]" %> value="<%= obj.name %>">

    <label>Description</label>
    <textarea type="text" class="input" name=<%= "#{@obj_name}[description]" %> ><%= obj.description %></textarea>

    <input type="text" class="none" name=<%= "#{@obj_name}[siteId]" %> value="<%= @siteId %>">




    <!--PLACEMENT ---------------------------------------------------->
    <% if placement['id'] %>
        <input type="text" class="none" name=<%= "#{@obj_name}[placement_id]" %> value="<%= placement['id'] %>">
    <% end %>

    <label>Size</label>
    <select id="ad_unit_select" type="text" class="input" name=<%= "#{@obj_name}[size_adUnit]" %> value="<%= placement.size_adUnit %>">
      <% Placement::ADUNIT_SELECT.each do |el| %>
          <option <%= "#{'selected' if placement.ad_unit_is(el[:value])}" %> value="<%= el[:value] %>"><%= el[:string] %></option>
      <% end %>
    </select>

    <!--Custom size-->
    <div id="custom_size" class="none">
      <label>Height</label>
      <input type="number" class="input" name=<%= "#{@obj_name}[size_height]" %> value="<%= placement.size_height %>">
      <label>Width</label>
      <input type="number" class="input" name=<%= "#{@obj_name}[size_width]" %>  value="<%= placement.size_width %>">
    </div>

    <!-- TODO TYPE SITE PLACEMENT etc - если мы получим от апи этот параметр тогда можно уже вставлять его в форму и при редактировании он останется прежним либо обновится
        но если он от апи не приходит то при редактировании тут в селекте не будет selected старого значения и значит может переписаться не верно или ошибка валидации вылезти - тогда надо хранить данные плэйсмента в базе что еще один гемор по сути
     -->

    <!--пока дефолт - в верстке не меняем и на бэке его не учитываем - TODO должен срабатывать дефолт CPM в епом-->
    <label>Payment Model</label>
    <select disabled="disabled" type="text" class="input" name=<%= "#{@obj_name}[payment_model]" %> value="<%= Placement::DEFAULT_PAYMENT_MODEL %>">
      <% PAYMENT_MODELS.each do |el| %>
          <option <%= "#{'selected' if el == 'CPM'}" %> value="<%= el %>"> <%= el %> </option>
      <% end %>
    </select>



    <label>Default code</label>
    <textarea type="text" class="input" name=<%= "#{@obj_name}[defaultCode ]" %> ><%= placement.defaultCode %></textarea>

    <input type="text" class="none" name=<%= "#{@obj_name}[zoneId]" %> value="<%= obj.id %>">
    <!--/PLACEMENT ---------------------------------------------------->



   </fieldset>
  <div class="but2"><input type="submit" class="button" value='<%= "#{standard_action == 'create' ? 'Add ' : 'Edit '} #{@obj_name}" %>' ></div>
</form>

app/views/publisher/zones/_inv_code_modal.html.erb
<!-- Предполагается что для любого объекта и даже действия СВОЕ модальное окно - мы не делаем запрос данных если в него они однажды были загружены-->
<div id='invCodeModal' class="reveal-modal" data-loaded="">
    <span class="close-reveal-modal close2"></span>
    <h2>Invocation Code</h2>
    <div class="spr2"></div>

    <div class="modal_content">

    </div>
</div>

app/views/publisher/zones/_zones_list.html.erb
<div class="list_wrapper">
  <table id='<%= "#{obj_name_plur}_created_list" %>' class="tab tab4 <%= 'none' if collection.count == 0 %>">
    <tbody>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Stats&nbsp;/&nbsp;Edit&nbsp;/&nbsp;Delete</th>
    </tr>

    <!-- TR TEMPLATE !!! - надо редактировать если меняем верстку-->
    <tr id="zone_tr_template" class="none">
      <td class="cat_td" data-name="zone[name]"> bbb </td>
      <td class="cat_td"> <a href="#">Show</a></td>
      <td>
        <a href="#" title="" class="st_1"></a>
        <a class="st_2 edit_zone" data-href="/publisher/zones/100/edit" data-model-name-camelize="Zone" data-model-name="zone" data-params="{'edit_obj':{'id':100,'name':'bbb'},'siteId':'29'}" href="javascript: void(0);" onclick="Traffex.standard.editInModal($(this), 100)"></a>

        <a class="st_4 delete_zone" data-action="zones_delete" data-confirm="Вы уверены?" data-method="delete" data-remote="true" data-standard-action="delete" href="/publisher/zones/100.json?siteId=29" rel="nofollow"></a>
      </td>
    </tr>
    <!--. /TR TEMPLATE-->

    <% collection.each do |obj| %>
        <tr id="<%= obj['id'] %>">
          <td class="cat_td" data-name='<%= "#{obj_name}[name]" %>' > <%= obj['name'] %> </td>
          <td class="cat_td" >
            <span class="links_td">
              <%= link_to 'Show', 'javascript: void(0);', onclick: "Traffex.zones.getCodeInModal($(this), #{obj['id']})", data: {href: get_code_publisher_zone_path(obj['id']), params: {zone: obj, siteId: @siteId}, model_name: 'code', model_name_camelize: 'Code'  } %>
            </span>
          </td>
          <td>
            <a href="#" title="" class="st_1"></a>
            <%= link_to '', 'javascript: void(0);', class: "st_2 edit_#{obj_name}", onclick: "Traffex.standard.editInModal($(this), #{obj['id']})", data: {href: public_send("edit_publisher_#{obj_name}_path", obj['id']), params: {edit_obj: obj, siteId: @siteId}, model_name: obj_name, model_name_camelize: obj_name.camelize  } %>

            <%= link_to '', public_send("publisher_#{obj_name}_path", obj['id'], siteId: @siteId, format: :json), method: 'delete', class: "st_4 delete_#{obj_name}", data: {confirm: t(:are_you_shure), standard_action:'delete', action: "#{obj_name_plur}_delete", remote: true}  %>
          </td>
        </tr>
    <% end %>

    </tbody>
  </table>

  <% if collection.count == 0 %>
      <p class="empty_info"><%= t :there_is_nothing %></p>
  <% else %>
      <ul class="page_nav">
        <li><a href="#" title="" class="prev_page"></a></li>
        <li><a href="#" title="" class="active">1</a></li>
        <li><a href="#" title="">2</a></li>
        <li><a href="#" title="">3</a></li>
        <li><a href="#" title="">4</a></li>
        <li><a href="#" title="">5</a></li>
        <li><a href="#" title="" class="next_page"></a></li>
      </ul>
  <% end %>

</div>

app/views/publisher/zones/edit.slim
= render "publisher/#{@obj_name_plur}/form", obj: @edit_obj, placement: @edit_placement, remote: true

app/views/publisher/zones/get_code.html.erb
<div class="modal_tabs">

  <div class="tabs_block custom_tabs" data-scope="#code_tabs">
    <ul class="tabs custom" >
      <li data-target="#js-tab-content" class="current"><a href="#" title="">JS</a></li>
      <li data-target="#iframe-tab-content" class=""><a href="#" title="">IFrame</a></li>
    </ul>
  </div>

  <div id="code_tabs">
    <div id="js-tab-content" class="box custom_tab visible" >
      <div id="js_code">
        <form class="form pp_form" >

          <textarea class="input" id="" name="" id="" cols="70" rows="20">
            <!-- BEGIN TAG - DO NOT MODIFY -->
            <script type="text/javascript">
                //<![CDATA[
                epom_key = <%= "#{@epom_key}" %>;
                epom_channel = "";
                epom_code_format = "ads-sync.js";
                epom_ads_host = "//n101adserv.com";
                epom_click = "";
                epom_custom_params = {};

                document.write("<script type='text\/javascript' src='"+(location.protocol == 'https:' ? 'https:' : 'http:') + "//n101adserv.com\/js/show_ads.js'><\/script>");
                //]]>
            </script>
            <!-- END TAG -->
          </textarea>

        </form>
      </div>
    </div>

    <div id="iframe-tab-content" class="box custom_tab " >
      <div id="iframe_code">
        <form class="form pp_form" >

          <textarea class="input" id="" name="" id="" cols="70" rows="20">
            <!-- BEGIN TAG - DO NOT MODIFY -->
            <script type="text/javascript">
                //<![CDATA[
                epom_key = <%= "#{@epom_key}" %>;
                epom_channel = "";
                epom_code_format = "ads";
                epom_ads_host = "//n68adserv.com";
                epom_click = "";
                epom_custom_params = {};
                epom_width = "468";
                epom_height = "60";

                document.write("<script type='text\/javascript' src='"+(location.protocol == 'https:' ? 'https:' : 'http:') + "//n68adserv.com\/js/show_ads.js'><\/script>");
                //]]>
            </script>
            <!-- END TAG -->
          </textarea>

        </form>
      </div>
    </div>
  </div>


</div>