config/routes.rb
Bannermaker::Application.routes.draw do
  resources :campaigns

  root 'landing#index'

  namespace :landing do
    get 'advertiser'
    get 'publisher'
    get 'about_us'
    get 'contacts'
  end

  resource :users, only: [] do
    get 'sign_up'
    get 'sign_in'
    delete 'sign_out'
    post 'create'
    post 'login'
  end

  namespace :publisher do
    root 'sites#index'

    resources :sites
    resources :zones do
      member do
        get 'get_code'
      end
    end

  end

  namespace :advertiser do
    root 'main#index'

    resource :payments, only: [] do
      get 'some_action'
    end
  end

  get 'othersite', to: 'other_site#index'
  get  'test',    to: 'other_site#test_get'
  post 'test',    to: 'other_site#test_post'
  put  'test',    to: 'other_site#test_put'
  delete 'test',  to: 'other_site#test_delete'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <!--<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>-->
          <i class="fa fa-times" onclick="Traffex.flash.close(this)"></i>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

<!--GLASH FROM JS-->
<div id="flash_js" class="alert none">
  <i class="fa fa-times" onclick="Traffex.flash.close(this)"></i>
  <div id="flash_msg"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html lang="en">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> <%= content_for?(:title) ? yield(:title) : t(:site_name) %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag("application", :media => "all") %>

        <!--ICONS-->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

        <!--[if lte IE 9]
            <%= stylesheet_link_tag "ie/ie_9", media: "all" %>
        <![endif]-->

        <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
        <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'%>
        <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'%>
        <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'%>
        <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'%>

        <%= include_gon %>
      </head>

      <body class="has-js" cz-shortcut-listen="true">
          <div class="wrapper" id="application_layout">

            <div class="wrap">

              <!-- header -->
              <header>
                <div class="wrap">
                  <a href="/" title="" class="logo">
                    <%= image_tag('logo.png') %>
                  </a>

                  <%= link_to 'Sing Out', sign_out_users_path(username: @current_user.username), method: 'delete', class: 'sign' %>"
                  <div class="support">
                    <div class="support_in">
                      <span></span>
                      <a href="#" title="">Support Name</a>
                      <small>Offline</small>
                    </div>
                  </div>
                </div>
              </header>
              <!-- /header -->

              <%= render partial: 'layouts/messages' %>

              <div class="content">
                <%= yield %>
              </div>


            </div>
            <div class="push"></div>
          </div>

          <!-- footer -->
          <footer>
            <div class="wrap">
              <a href="#" title="" class="logo_small">
                <%= image_tag('logo_small.png') %>
              </a>
              <ul class="foot_nav">
                <li><a href="#" title="">FAQ</a></li>
                <li><a href="#" title="">Help</a></li>
                <li><a href="#" title="">Terms</a></li>
                <li><a href="#" title="">Contacts</a></li>
              </ul>
              <p class="copy">© TrafficExchange 2014</p>
              <ul class="contacts">
                <li><span class="icq"></span>ICQ: 208444080</li>
                <li><span class="skype"></span>Skype: traff-ex</li>
                <li><span class="phone"></span>+ 1 (356) 45-46-546</li>
              </ul>
              <div class="clearing"></div>
            </div>
          </footer>
          <!-- /footer -->

          <!-- MODALS -->
          <div id="modals">
            <%= yield :modals %>
          </div>
          <!-- /MODALS -->

          <%= javascript_include_tag "application" %>
          <!--[if lt IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js")</script><![endif]-->

          <!--WEINRE DEBUG-->
          <!--= javascript_include_tag "http://192.168.1.49:8080/target/target-script-min.js#anonymous"-->

      </body>

  </html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
  <html lang="en">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> <%= content_for?(:title) ? yield(:title) : t(:site_name) %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag("landing/landing", :media => "all") %>

        <!--ICONS-->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

        <!--[if lte IE 9]
            <%= stylesheet_link_tag "ie/ie_9", media: "all" %>
        <![endif]-->

        <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
        <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'%>
        <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'%>
        <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'%>
        <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'%>

        <%= include_gon %>
      </head>

      <body class="inner_body" cz-shortcut-listen="true">
          <div class="wrapper" id="landing_layout">

              <!-- header -->
              <header class="main_head" id="main_head">
                <div class="wrap">
                  <a href="/" title="" class="logo_main">
                    <%= image_tag 'logo_main.png' %>
                  </a>
                  <div class="head_buttons">
                    <a href="javascript:void(0);" title="Login" class="button2" data-reveal-id="loginModal" data-animation="fade">Login</a>
                    <a href="javascript:void(0);" title="Sign Up" class="button2 b6" data-reveal-id="signModal" data-animation="fade">Sign Up</a>
                  </div>
                  <ul class="top_menu">
                    <li>
                      <%= link_with_active_class('Advertiser', landing_advertiser_path) %>
                    </li>
                    <li>
                      <%= link_with_active_class('Pulisher', landing_publisher_path) %>
                    </li>
                    <li>
                      <%= link_with_active_class('About us', landing_about_us_path) %>
                    </li>
                    <li>
                      <%= link_with_active_class('Contacts', landing_contacts_path) %>
                    </li>
                  </ul>
                </div>
              </header>
              <!-- /header -->

              <%= render partial: 'layouts/messages' %>
              <%= yield %>


            <div class="push"></div>
          </div>


          <!-- footer -->
          <footer class="main_foot">
            <div class="wrap">
              <a href="/" title="" class="link_home"></a>
              <ul class="foot_nav2">
                <li>
                  <%= link_with_active_class('Advertiser', landing_advertiser_path) %>
                </li>
                <li>
                  <%= link_with_active_class('Pulisher', landing_publisher_path) %>
                </li>
                <li>
                  <%= link_with_active_class('About us', landing_about_us_path) %>
                </li>
                <li>
                  <%= link_with_active_class('Contacts', landing_contacts_path) %>
                </li>
              </ul>
              <p class="terms">Be sure to take a look to our <a href="#" title="">Terms of Use</a> and <a href="#" title="Privacy Policy">Privacy Policy</a></p>
              <div class="clearing"></div>
            </div>
          </footer>
          <!-- /footer -->

          <div id="modals">
            <% if !current_page?(sign_up_users_path) && (request.path != '/users/create')  %>
                <!-- sign up modal -->
                <div id="signModal" class="reveal-modal mod2 none">
                  <span class="close-reveal-modal close3"></span>
                  <%= render 'shared/sign_up_form', user: (@user || User.new), remote_sign_up: true %>
                </div>
                <!-- /sign up modal -->
            <% end %>

            <% if !current_page?(sign_in_users_path) && (request.path != '/users/login') %>
                <!-- login modal -->
                <div id="loginModal" class="reveal-modal mod2 none">
                  <span class="close-reveal-modal close3"></span>

                  <%= render 'shared/sign_in_form', user: (@user || User.new), remote_sign_in: true %>
                </div>
                <!-- /login modal -->
            <% end %>
          </div>

          <%= javascript_include_tag "landing/landing" %>
          <!--[if lt IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js")</script><![endif]-->

          <!--WEINRE DEBUG-->
          <!--= javascript_include_tag "http://192.168.1.49:8080/target/target-script-min.js#anonymous"-->

      </body>
  </html>